C# index & variables are updated
brainchildservices/LearnCsharp pull request #4
Opened 2021-04-21 13:16 UTC by SijoGeorge7012

![image](https://user-images.githubusercontent.com/78071547/115559489-61f14b00-a2d1-11eb-861a-a71c17aa644b.png)
![image](https://user-images.githubusercontent.com/78071547/115559569-6e75a380-a2d1-11eb-891d-65a5a4b6dceb.png)
![image](https://user-images.githubusercontent.com/78071547/115559604-76354800-a2d1-11eb-9c1b-a057fc703c0d.png)
![image](https://user-images.githubusercontent.com/78071547/115559645-7fbeb000-a2d1-11eb-87e8-a3e35c85da0c.png)
![image](https://user-images.githubusercontent.com/78071547/115559679-88af8180-a2d1-11eb-8266-2597073f46d1.png)
![image](https://user-images.githubusercontent.com/78071547/115559726-9238e980-a2d1-11eb-95eb-12129a176ab3.png)
![image](https://user-images.githubusercontent.com/78071547/115559747-9b29bb00-a2d1-11eb-905a-2839324bafea.png)
![image](https://user-images.githubusercontent.com/78071547/115559797-a5e45000-a2d1-11eb-91c0-217ac566bb40.png)

2021-04-22 10:56 UTC, wandercode requested changes
each variable should have a to do task

2021-04-22 10:56 UTC, wandercode commented on 002variables.html
> +                </section>
include a table as a new slide of different types of variables (include the previous table created)

2021-04-22 12:47 UTC, rohithkrajan approved these changes

2021-04-23 04:19 UTC, wandercode approved these changes

2021-04-23 04:22 UTC, wandercode requested changes
try to arrange the code well aligned

2021-04-23 04:22 UTC, wandercode commented on 001syntsx.html
> +<!doctype html>
change file name to correct spelling

2021-04-23 04:36 UTC, SijoGeorge7012 commented on 001syntsx.html
> +<!doctype html>
changed file name
please review

2021-04-26 04:16 UTC, wandercode commented
LGTM

2021-04-26 04:17 UTC, wandercode approved these changes

2021-04-26 04:19 UTC, merged