added types casting file
brainchildservices/LearnCsharp pull request #9
Opened 2021-04-30 06:51 UTC by SijoGeorge7012

![image](https://user-images.githubusercontent.com/78071547/116658930-6642f580-a9ae-11eb-8dc3-6c088ad54f40.png)
![image](https://user-images.githubusercontent.com/78071547/116658946-6f33c700-a9ae-11eb-9ca2-9b759271606a.png)
![image](https://user-images.githubusercontent.com/78071547/116658963-75c23e80-a9ae-11eb-87ce-c2f633316899.png)
![image](https://user-images.githubusercontent.com/78071547/116658973-7c50b600-a9ae-11eb-95a1-0613d3b7c3e8.png)
![image](https://user-images.githubusercontent.com/78071547/116658989-8377c400-a9ae-11eb-8920-413f06e2d2e4.png)
![image](https://user-images.githubusercontent.com/78071547/116659005-896da500-a9ae-11eb-8392-7fb8b499ddf7.png)
etc

2021-04-30 08:03 UTC, VishnuKulakkattu requested changes

2021-04-30 08:03 UTC, VishnuKulakkattu commented on 004typecasting.html
> +                    <p>Type conversion is converting one type of data to another type. It is also known as Type Casting. In C#</p>
Correct the sentence Please!

2021-04-30 08:14 UTC, wandercode requested changes

2021-04-30 08:14 UTC, wandercode commented on 004typecasting.html
> +                    <p> These conversions are performed by C# in a type-safe manner. For example, are conversions from smaller to larger integral types and conversions from derived classes to base cl
change text after 'For example'
     to - "conversions from smaller to larger integral types"

2021-04-30 08:18 UTC, wandercode requested changes

2021-04-30 08:18 UTC, wandercode commented on 004typecasting.html
> +                        Console.WriteLine(myDouble);//Output 9
please add right and wrong syntax for every examples .
please dont forget to mention reason for the error in wrong syntax and also to display the output.

2021-05-02 22:09 UTC, wandercode requested changes

2021-05-02 22:09 UTC, wandercode commented on 004typecasting.html
> +                        Console.WriteLine(Convert.ToString(myBool));   // convert bool to string
please show the outputs

2021-05-02 22:09 UTC, wandercode commented on 004typecasting.html
> +                        Console.WriteLine(Convert.ToString(myBoo));   // wrong declaration to convert bool to string, unassign variable
please show the output

2021-05-03 04:44 UTC, wandercode requested changes

2021-05-03 04:44 UTC, wandercode commented on 004typecasting.html
> +                    </p>
please add examples for each Int32.parse, Double.parse, float.parse etc, (right and wrong syntax)

2021-05-03 11:32 UTC, wandercode requested changes

2021-05-03 11:32 UTC, wandercode commented on 004typecasting.html
> +                </p>
please reduce the size of  paragraph.

2021-05-03 11:32 UTC, wandercode commented on 004typecasting.html
> +            </div>
please add excercises for .Parse method

2021-05-04 06:28 UTC, wandercode commented
LGTM

2021-05-04 06:28 UTC, wandercode approved these changes

2021-05-04 06:53 UTC, VishnuKulakkattu requested changes

2021-05-04 06:53 UTC, VishnuKulakkattu commented on 004typecasting.html
> +                <p style="font-size:30px;">
Please move these styling to css, in every code

2021-05-05 04:53 UTC, wandercode commented
LGTM

2021-05-05 05:07 UTC, aneeshs005 commented
@SijoGeorge7012 You should include more slides for when the implicit casting occurs when explicit casting occurs. (Eg shown in w3 school)
Slides for different ways for casting. Eg: casting using (int), (double), Convert function, Parse method, TryParse method
What is the common error that occurs when you don't do explicit conversion correctly?

2021-05-07 09:17 UTC, aneeshs005 reviewed
Where are the 6 exercises which you did?
I asked you to add that as well, right?

2021-05-07 09:17 UTC, aneeshs005 commented on 004typecasting.html
> +                                Console.WriteLine(Double.parse(a)); // Double.Parse not Double.parse
You have given right syntax as wrong syntax

2021-05-10 04:41 UTC, aneeshs005 commented
@wandercode @VishnuKulakkattu @rohithkrajan Looks good to me

2021-05-10 06:02 UTC, rohithkrajan approved these changes

2021-05-10 08:59 UTC, wandercode approved these changes

2021-05-10 09:00 UTC, wandercode approved these changes

2021-05-10 09:12 UTC, VishnuKulakkattu approved these changes

2021-05-10 09:16 UTC, merged